config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :chats do
    resources :messages, only: %i[create]
  end
  resource :notifications, only: %i[create]
  
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'chats', to: 'chats#index'
      post 'chats/:chat_id/messages', to: 'messages#create'
    end
  end

  root 'chats#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
	has_many :messages
	validates :name, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  after_create_commit :notificate
  validates :body, presence: true

  private
  def notificate
    broadcast_append_to self.chat
    Notification.all.each do |notification| 
      notification.notificate("new message at #{self.chat.name} HAas")
    end
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
	belongs_to :user

	def notificate(message)
		WebPush.payload_send(
			message:  message, 
			endpoint: endpoint,
			p256dh:   p256dh_key,
			auth: 	  auth_key,
			vapid: {
				private_key: Rails.application.credentials.dig(:webpush, :private_key), 
				public_key:  Rails.application.credentials.dig(:webpush, :public_key)
			})
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notifications
  
  def username
    self.email.split('@')[0].capitalize
  end
end

app/controllers/api/v1/chats_controller.rb
class Api::V1::ChatsController < ApplicationController
	def index
    render json: Chat.all
	end
end

app/controllers/api/v1/messages_controller.rb
class Api::V1::MessagesController < ApplicationController
	def create	
		chat = Chat.find params[:chat_id]
		message = chat.messages.new(message_params)
    if message.save
    	render json: message, status: 201
    else
      render json: { errors: message.errors }, status: 422
    end
	end

	private

	def message_params
		params.require(:message).permit(:author, :body).merge(author: 'Unknown')
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
	before_action :authenticate_user!
	
	def index
		@chats = Chat.all
	end

	def new
		@chat = Chat.new
	end

	def show
		@chat = Chat.find params[:id]
		@messages = @chat.messages.order(created_at: :desc)
		@message = @chat.messages.new
	end

	def create
    chat = Chat.new(chat_params)

    if chat.save
      redirect_to chat
    else
      render :new, status: :unprocessable_entity
    end
	end

	private

	def chat_params
		params.require(:chat).permit(:name)
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def create	
		chat = Chat.find params[:chat_id]
		message = @chat.messages.new(message_params)
    if message.save
    	redirect_to chat
    else
      redirect_to chat, status: :unprocessable_entity
    end
	end

	private

	def message_params
		params.require(:message).permit(:author, :body).merge(author: current_user.email)
	end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	skip_before_action :verify_authenticity_token

	def create	
		return update if current_user.notifications != []
			
		notification = current_user.notifications.build(
				endpoint: 	params[:endpoint],
				auth_key: 	params[:keys][:auth],
				p256dh_key: params[:keys][:p256dh]
			)

		if notification.save
			render json: notification
		else
			render json: notification.errors.full_messages
		end
	end

	def update
		notification = current_user.notifications.last

		notification.update(
				endpoint: 	params[:endpoint],
				auth_key: 	params[:keys][:auth],
				p256dh_key: params[:keys][:p256dh]
			)
		if notification.save
			render json: notification
		else
			render json: notification.errors.full_messages
		end
	end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chats/index.html.erb
<% content_for :head do %>
  <h3>Chats</h3>
<% end %>

<div class="row">
	<p> 
		Hello, <%= current_user.username %> 
	</p>
</div>
<% @chats.each do |chat| %>
	<div class="d-flex justify-content-between bd-highlight mb-3"> 
		<div class="p-2 bd-highlight">
			<%=chat.name%>
    </div>
    <div class="p-2 bd-highlight">
			<%= link_to 'Open', chat_path(chat.id), class: 'btn btn-primary btn-sm' %>
		</div>
	</div>
	<hr>	
<% end %>
<div>
	<%= link_to 'New', new_chat_path, class: 'btn btn-success' %>
</div>

app/views/chats/new.html.erb
<% content_for :head do %>
  <h3>New chat</h3>
<% end %>

<%= form_with model: @chat do |form| %>
  <div>
    <%= form.label :name, class: 'mb-2' %><br>
    <%= form.text_field :name, class: 'mb-2' %>
    <% @chat.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit%>
  </div>
<% end %>

app/views/chats/show.html.erb
<% content_for :head do %>
  <h3><%= @chat.name %></h3>
<% end %>

<%= turbo_stream_from @chat %>
<div id="chat">
	<div id="messages">
	  <%= render @messages %>
	</div>

	<div class="form-group msg-form">
	  <%= form_with(model: [@chat, @message], remote: true, class:'d-flex') do |f| %>
	    <%= f.text_field :body, autocomplete: 'off', class: 'm-1'  %>
	    <%= f.submit 'Send', class: 'btn btn-primary m-1' %>	
	  <% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if current_user %>
      <div class="d-flex justify-content-around bd-highlight mb-3">
        <div class="p-2 bd-highlight">
          <%= link_to 'Talker', root_path, class: 'btn btn-primary'%>
        </div>
        <div class="p-2 bd-highlight">
          <%= yield :head %>
        </div>
        <div class="p-2 bd-highlight">
          <%= button_to 'log out', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
        </div>
      </div>
      <%= render 'shared/script'%>
    <% end %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="d-flex justify-content-between bd-highlight mb-3"> 
	<div class="p-2 bd-highlight">
		<figure>
		  <blockquote class="blockquote">
		    <p><%= message.body %></p>
		  </blockquote>
		  <figcaption class="blockquote-footer">
		    <%= message.author %>
		  </figcaption>
		</figure>			
  </div>
  <div class="p-2 bd-highlight">
  	<small class="text-muted"><%= message.created_at %></small>
	</div>
</div>

app/views/shared/_script.html.erb
<script type="text/javascript">
Notification.requestPermission();
const vapidPublicKey = new Uint8Array(<%= Base64.urlsafe_decode64(Rails.application.credentials.dig(:webpush, :public_key)).bytes %>);
if (navigator.serviceWorker) {
  navigator.serviceWorker.register('/service-worker.js')
  .then(function(reg) {
    navigator.serviceWorker.ready.then((serviceWorkerRegistration) => {

      serviceWorkerRegistration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: vapidPublicKey
      }).then(async function(sub) {
        const data = await fetch('/notifications', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify(sub),
        }).then(r=>r.json());
        console.log(data);
      })
    });
    console.log('Service worker change, registered the service worker');
  });
} else {
  console.error('Service worker is not supported in this browser');
}
</script>